validation_outdir: data/validation_datasets
outdir: "data/datasets"
min_l: 200
min_q: 10
validation_datasets:
  simulated_1_nanomotif_microbemod:
    assembly: data/datasets/simulated_1_nanomotif_microbemod/concatenated_assembly.fasta
    fastq: data/datasets/simulated_1_nanomotif_microbemod/concatenated_reads.fastq
  simulated_2_nanomotif:
      assembly: data/datasets/simulated_2_nanomotif/concatenated_assembly.fasta
      fastq: data/datasets/simulated_2_nanomotif/concatenated_reads.fastq
  simulated_3_lognormal:
    assembly: data/datasets/simulated_3_lognormal/assembly.fasta
    fastq: data/datasets/simulated_3_lognormal/concatenated.fastq