validation_outdir: data/validation_datasets
outdir: "data/datasets"
min_l: 200
min_q: 10
validation_datasets:
  simulated_3_lognormal:
    assembly: data/datasets/simulated_3_lognormal/assembly.fasta
    fastq: data/datasets/simulated_3_lognormal/concatenated.fastq
  simulated_4_lognormal_20-100x:
    assembly: data/datasets/simulated_4_lognormal_20-100x/assembly.fasta
    fastq: data/datasets/simulated_4_lognormal_20-100x/concatenated.fastq
