outdir: output/benchmarks/detect_contamination/test
baseline_dir: output/baseline/
partition: general
mode: detect_contamination


# Settings for nanomotif_dev
mean_methylation_cutoff: 0.25
n_motif_contig_cutoff: 10
n_motif_bin_cutoff: 500

samples:
  simulated_3_lognormal:
    assembly:  data/datasets/simulated_3_lognormal/assembly.fasta
    eukfilt_assembly: data/datasets/simulated_3_lognormal/eukfilt_assembly.fasta
    pileup: data/datasets/simulated_3_lognormal/mod_pileup.bed
    benchmarks:
      original_contig_bin: data/datasets/simulated_3_lognormal/contig_mapping/mapped_contig_bin.tsv
      benchmark_0_shuffle_1_contig: files/benchmarks/benchmark_0_shuffle_1_contig.tsv
      benchmark_1_shuffle_1_contig: files/benchmarks/benchmark_1_shuffle_1_contig.tsv
      benchmark_2_shuffle_1_contig: files/benchmarks/benchmark_2_shuffle_1_contig.tsv
      # benchmark_3_shuffle_1_contig: files/benchmarks/benchmark_3_shuffle_1_contig.tsv
      # benchmark_4_shuffle_1_contig: files/benchmarks/benchmark_4_shuffle_1_contig.tsv

