outdir: output/benchmarks/include_contigs
baseline_dir: output/baseline/
partition: shared
n_benchmarks: 50


# Settings for nanomotif_dev
min_valid_read_cov: 3

samples:
  fragmentation_benchmark_20kb_1600kb:
    assembly: data/datasets/fragmentation_benchmark_20kb_1600kb/concatenated_assembly.fasta
    eukfilt_assembly: data/datasets/fragmentation_benchmark_20kb_1600kb/concatenated_assembly.fasta
    pileup: data/datasets/fragmentation_benchmark_20kb_1600kb/mod_pileup.bed
    bin_motifs: data/datasets/fragmentation_benchmark_20kb_1600kb/bin-motifs.tsv
    contig_bin: data/datasets/fragmentation_benchmark_20kb_1600kb/contig_bin.tsv
  fragmentation_benchmark_20kb_1600kb_w_motif_discovery:
    assembly: data/datasets/fragmentation_benchmark_20kb_1600kb/concatenated_assembly.fasta
    eukfilt_assembly: data/datasets/fragmentation_benchmark_20kb_1600kb/concatenated_assembly.fasta
    pileup: data/datasets/fragmentation_benchmark_20kb_1600kb/mod_pileup.bed
    bin_motifs: data/datasets/fragmentation_benchmark_20kb_1600kb/motif_discovery/bin-motifs.tsv
    contig_bin: data/datasets/fragmentation_benchmark_20kb_1600kb/contig_bin.tsv

