
outdir: data/real_communities/
partition: default-op


samples:
  # simulated_4_lognormal_20-100x:
  #   assembly:  data/datasets/simulated_4_lognormal_20-100x/assembly.fasta
  #   eukfilt_assembly: data/datasets/simulated_4_lognormal_20-100x/eukfilt_assembly.fasta
  #   pileup: data/datasets/simulated_4_lognormal_20-100x/mod_pileup.bed
  #   bin_motifs: data/datasets/simulated_4_lognormal_20-100x/bin-motifs.tsv
  #   contig_bin: data/datasets/simulated_4_lognormal_20-100x/contig_mapping/mapped_contig_bin.tsv
  # fragmentation_benchmark_20kb:
  #   assembly: data/datasets/fragmentation_benchmark_20kb/concatenated_assembly.fasta
  #   eukfilt_assembly: data/datasets/fragmentation_benchmark_20kb/concatenated_assembly.fasta
  #   pileup: data/datasets/fragmentation_benchmark_20kb/mod_pileup.bed
  #   bin_motifs: data/datasets/fragmentation_benchmark_20kb/bin-motifs.tsv
  #   contig_bin: data/datasets/fragmentation_benchmark_20kb/contig_bin.tsv
  # fragmentation_benchmark_20kb_1800kb:
  #   assembly: data/datasets/fragmentation_benchmark_20kb_1800kb/concatenated_assembly.fasta
  #   eukfilt_assembly: data/datasets/fragmentation_benchmark_20kb_1800kb/concatenated_assembly.fasta
  #   pileup: data/datasets/fragmentation_benchmark_20kb_1800kb/mod_pileup.bed
  #   bin_motifs: data/datasets/fragmentation_benchmark_20kb_1800kb/bin-motifs.tsv
  #   contig_bin: data/datasets/fragmentation_benchmark_20kb_1800kb/contig_bin.tsv
  # fragmentation_benchmark_20kb_1800kb_combined:
  #   assembly: data/datasets/fragmentation_benchmark_20kb_1800kb_combined/concatenated_assembly.fasta
  #   eukfilt_assembly: data/datasets/fragmentation_benchmark_20kb_1800kb_combined/concatenated_assembly.fasta
  #   pileup: data/datasets/fragmentation_benchmark_20kb_1800kb_combined/mod_pileup.bed
  #   bin_motifs: data/datasets/fragmentation_benchmark_20kb_1800kb_combined/bin-motifs.tsv
  #   contig_bin: data/datasets/fragmentation_benchmark_20kb_1800kb_combined/contig_bin.tsv
  fecal_simple_recovered:
    assembly: data/real_communities/fecal_simple_recovered/mmlong2_lite/results/mmlong2_assembly.fasta
    pileup: data/real_communities/fecal_simple_recovered/mod_pileup.bed
    contig_bin: data/real_communities/fecal_simple_recovered/mmlong2_lite/tmp/binning/contig_bin.tsv
  fragmentation_benchmark_20kb_1600kb:
    assembly: data/datasets/fragmentation_benchmark_20kb_1600kb/concatenated_assembly.fasta
    pileup: data/datasets/fragmentation_benchmark_20kb_1600kb/mod_pileup.bed
    contig_bin: data/datasets/fragmentation_benchmark_20kb_1600kb/contig_bin.tsv

